name: Test and Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     # 1. Récupérer le code source
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     # 2. Installer Node.js (ici version 16, à adapter si nécessaire)
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'

  #     # 3. Installer les dépendances
  #     - name: Install dependencies
  #       run: npm install

  #     # 5. Lancer le build de l'application Angular (production)
  #     - name: Build Angular App
  #       run: npm run build 

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no root@62.72.36.125	 'bash -s' < deploy.sh
